# do not touch this line
configVersion: 2

description: moodify
keywords: moodify
name: moodify
displayName: Moodify

dataTypes:
  playlist: string

services:
  moodify:
    engine: detection
    type: demographics
