# do not touch this line
configVersion: 2

name: moodify

description: Moodify your day! Listen to musics on Spotify according to your mood.


keywords:
  - moodify
  - spotify

dataTypes:
  playlist: string

icon: http://i.imgur.com/YIu8Mfv.png

imageUrls:
  - http://i.imgur.com/HdbIsbG.jpg
  - http://i.imgur.com/HdbIsbG.jpg

galleryUrl: http://i.imgur.com/YIu8Mfv.png

inputTest:
  control: input
  event: testInput
  value: 'type text'
  label: 'Test Input'


displayName: Moodify

categories:
  - Entertainment

services:
  moodify:
    engine: detection
    type: demographics
