# do not touch this line
configVersion: 2

name: moodify

description: Moodify your day! Listen to musics on Spotify according to your mood.


imageUrls:
  - http://i.imgur.com/HdbIsbG.jpg
  - http://i.imgur.com/HdbIsbG.jpg

galleryUrl:  http://i.imgur.com/YIu8Mfv.png



keywords:
  - moodify
  - spotify

displayName: Moodify
categories:
  - Entertainment

dataTypes:
  playlist: string

services:
  moodify:
    engine: detection
    type: demographics
