# do not touch this line
configVersion: 2

description: App verify you mood, sending playlist for email.
keywords: Spotify
name: moodify
displayName: Moodify

dataTypes:
  playlist: string

services:
  moodify:
    engine: detection
    type: demographics
